src/test2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'main_page/index'
  get 'elections/index'
  get 'candidates/index'

  resources :pages
  resources :candidates
  resources :elections

  root to: 'main_page#index'
end

src/test2/app/models/application_record.rb
# Project name: SOLVER
# Description: Create webapp that encourages students to vote and register to vote. Presents information
# about how to register and vote, and list of upcoming elections and candidates for those elections.
# Filename: application_record.rb
# Description: model for application MVC structure
# Last modified on: 11/24/2019

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

src/test2/app/models/candidates.rb
# Project name: SOLVER
# Description: Create webapp that encourages students to vote and register to vote. Presents information
# about how to register and vote, and list of upcoming elections and candidates for those elections.
# Filename: candidates.rb
# Description: model for candidates MVC structure
# Last modified on: 11/24/2019

class Candidates < ApplicationRecord
  validates :name, presence: true, #must have name to submit
            length: {minimum: 5}
  belongs_to :election, optional: true #association - candidate belong to election

end

src/test2/app/models/election.rb
# Project name: SOLVER
# Description: Create webapp that encourages students to vote and register to vote. Presents information
# about how to register and vote, and list of upcoming elections and candidates for those elections.
# Filename: election.rb
# Description: model for candidates MVC structure, set up associations and validation
# Last modified on: 11/24/2019

class Election < ApplicationRecord
  has_many :candidates #association - election has many candidates

  validates :election_title, presence: true, #title, type, date, and description must be present to submit/edit election
            length: {minimum: 5}
  validates :election_type, presence: true
  #validates :election_date_must_be_future, presence: true
  validates :description, presence: true


  def election_date_must_be_future #function to validate date
    if election_date.present? && election_date < Date.today
      errors.add(:election_date, "cannot be in the past")
      not_in_past = true
    end
  end

end

src/test2/app/models/page.rb
# Project name: SOLVER
# Description: Create webapp that encourages students to vote and register to vote. Presents information
# about how to register and vote, and list of upcoming elections and candidates for those elections.
# Filename: page.rb
# Description: model for page MVC structure
# Last modified on: 11/24/2019

class Page < ApplicationRecord
end

src/test2/app/models/user.rb
# Project name: SOLVER
# Description: Create webapp that encourages students to vote and register to vote. Presents information
# about how to register and vote, and list of upcoming elections and candidates for those elections.
# Filename: user.rb
# Description: model for user MVC structure, imported from devise
# Last modified on: 11/24/2019

class User < ApplicationRecord #devise user object
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

src/test2/app/controllers/application_controller.rb
# Project name: SOLVER
# Description: Create webapp that encourages students to vote and register to vote. Presents information
# about how to register and vote, and list of upcoming elections and candidates for those elections.
# Filename: application_controller
# Description: Controller for application MVC structure
# Last modified on: 11/24/2019


class ApplicationController < ActionController::Base
end

src/test2/app/controllers/candidates_controller.rb
# Project name: SOLVER
# Description: Create webapp that encourages students to vote and register to vote. Presents information
# about how to register and vote, and list of upcoming elections and candidates for those elections.
# Filename: candidates_controller
# Description: Controller for candidate MVC structure
# Last modified on: 11/24/2019


class CandidatesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index] #authenticate user before all actions

  http_basic_authenticate_with name: "admin", password: "password", except: [:index, :show] #restrict view of non-admin user

  def index #function to create index of all candidates
    @candidates = Candidates.all
  end

  def show #function to show specific candidate
    @candidates = Candidates.find(params[:id])
  end

  def new #function to create new candidate
    @candidates = Candidates.new
  end

  def edit #function to edit candidate
    @candidates = Candidates.find(params[:id])
  end

  def create #function that references new to create new candidate
    @candidates = Candidates.new(candidate_params)

    if @candidates.save
      redirect_to @candidates
    else
      render 'new'
    end
  end

  def destroy #function to delete candidate
    @candidates = Candidates.find(params[:id])
    @candidates.destroy

    redirect_to candidates_path
  end

  def update #function to update candidate
    @candidates = Candidates.find(params[:id])

    if @candidates.update(candidate_params)
      redirect_to @candidates
    else
      render 'edit'
    end
  end

  private
  def candidate_params #function defining parameters for a candidate
    params.require(:candidates).permit(:name, :political_affiliation, :info)
  end
end

src/test2/app/controllers/elections_controller.rb
# Project name: SOLVER
# Description: Create webapp that encourages students to vote and register to vote. Presents information
# about how to register and vote, and list of upcoming elections and candidates for those elections.
# Filename: elections_controller
# Description: Controller for election MVC structure
# Last modified on: 11/24/2019


class ElectionsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index] #authenticate user before all actions

  http_basic_authenticate_with name: "admin", password: "password", except: [:index, :show] #restrict view of non-admin users

  def index #function to create index of all elections
    @elections = Election.all
  end

  def show #function to show specific election
    @election = Election.find(params[:id])
  end

  def new #function to create new election
    @election = Election.new
  end

  def edit #function to edit election details
    @election = Election.find(params[:id])
  end

  def create #function referencing new to create new election
    @election = Election.new(election_params)

    if @election.save
      redirect_to @election
    else
      render 'new'
    end
  end

  def destroy #function to delete election
    @election = Election.find(params[:id])
    @election.destroy

    redirect_to elections_path
  end

  def update #function to update election
    @election = Election.find(params[:id])

    if @election.update(election_params)
      redirect_to @election
    else
      render 'edit'
    end
  end

  private
  def election_params #function defining parameters for an election
    params.require(:election).permit(:election_title, :election_date, :election_type, :description)
  end
end

src/test2/app/controllers/main_page_controller.rb
# Project name: SOLVER
# Description: Create webapp that encourages students to vote and register to vote. Presents information
# about how to register and vote, and list of upcoming elections and candidates for those elections.
# Filename: main_page_controller
# Description: Controller for main-page MVC structure
# Last modified on: 11/24/2019

class MainPageController < ApplicationController
  def index
  end
end

src/test2/app/controllers/pages_controller.rb
# Project name: SOLVER
# Description: Create webapp that encourages students to vote and register to vote. Presents information
# about how to register and vote, and list of upcoming elections and candidates for those elections.
# Filename: pages_controller
# Description: Controller for pages_controller MVC unit
# Last modified on: 11/24/2019

class PagesController < ApplicationController
  def new
  end
end

src/test2/app/helpers/candidates_helper.rb
module CandidatesHelper
end

src/test2/app/helpers/elections_helper.rb
module ElectionsHelper
end

src/test2/app/helpers/main_page_helper.rb
module MainPageHelper
end

src/test2/app/helpers/pages_helper.rb
module PagesHelper
end

src/test2/app/views/candidates/edit.html.erb
<!--
// Project name: SOLVER
// Description: Create webapp that encourages students to vote and register to vote. Presents information
    about how to register and vote, and list of upcoming elections and candidates for those elections.
// Filename: candidates\edit.html.erb
// Description: page to edit election details
// Last modified on: 11/24/2019
-->


<h1>Edit Candidate</h1>

<%= form_with(model: @candidates, local: true) do |form| %>

  <% if @candidates.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@candidates.errors.count, "error") %> prohibited
        this candidate from being saved:
      </h2>
      <ul>
        <% @candidates.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :political_affiliation%><br>
    <%= form.text_field :political_affiliation %>
  </p>

  <p>
    <%= form.label :info %><br>
    <%= form.text_area :info %>
  </p>

  <p>
    <%= form.label :election%><br>
    <%= form.collection_select :attached_election, Election.all, :id, :election_title%>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back to Election', elections_path %>

src/test2/app/views/candidates/index.html.erb
<!--
// Project name: SOLVER
// Description: Create webapp that encourages students to vote and register to vote. Presents information
    about how to register and vote, and list of upcoming elections and candidates for those elections.
// Filename: candidates\index.html.erb
// Description:  Presents list of candidates after they've been created, and ability to edit and delete if user is admin
// Last modified on: 11/24/2019
-->


<h1>List of Candiates</h1>

<br>

<!-- Search form -->
<form class="form-inline">
  <i class="fas fa-search" aria-hidden="true"></i>
  <input class="form-control form-control-sm ml-3 w-70" type="text" placeholder="Search"
         aria-label="Search">
</form>

<br>

<table class = "table table-striped">
  <tr>
    <th>Candidate</th>
    <th>Affiliation</th>
    <th>Info</th>
  </tr>


  <% @candidates.each do |candidate| %>
    <tr>
      <td><%= candidate.name %></td>
      <td><%= candidate.political_affiliation%></td>
      <td><%= candidate.info %></td>
      <td><%= link_to 'Show', candidate_path(candidate) %></td>
      <%if current_user && current_user.admin%>
      <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
      <td><%= link_to 'Delete', candidate_path(candidate),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<p>
  <%if current_user && current_user.admin%>
  <%= link_to 'Add candidates', new_candidate_path %>
  <% end %>
</p>


<p>
  <%= link_to 'Back to Main Page', main_page_index_path %>
</p>

src/test2/app/views/candidates/new.html.erb
<!--
// Project name: SOLVER
// Description: Create webapp that encourages students to vote and register to vote. Presents information
    about how to register and vote, and list of upcoming elections and candidates for those elections.
// Filename: candidates\new.html.erb
// Description: page to create new candidate and associate to election
// Last modified on: 11/24/2019
-->


<title>Add Candidate</title>



<h1>New Candidate</h1>

<%= form_with scope: :candidates, url: candidates_path, local: true do |form| %>

  <% if @candidates.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@candidates.errors.count, "error") %> prohibited
        this candidate from being added:
      </h2>
      <ul>
        <% @candidates.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :political_affiliation%><br>
    <%= form.text_field :political_affiliation %>
  </p>

  <p>
    <%= form.label :info%><br>
    <%= form.text_area :info %>
  </p>

  <p>
    <%= form.label :election%><br>
    <%= form.collection_select :attached_election, Election.all, :id, :election_title%>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>



<%= link_to 'Back to Main Page', main_page_index_path %>

src/test2/app/views/candidates/show.html.erb
<!--
// Project name: SOLVER
// Description: Create webapp that encourages students to vote and register to vote. Presents information
    about how to register and vote, and list of upcoming elections and candidates for those elections.
// Filename: candidates\show.html.erb
// Description: Shows details of specific candidate
// Last modified on: 11/24/2019
-->

<p>
  <strong>Name:</strong>
  <%= @candidates.name %>
</p>

<p>
  <strong>Political Affiliation:</strong>
  <%= @candidates.political_affiliation %>
</p>

<p>
  <strong>Info:</strong>
  <%= @candidates.info %>
</p>

<p>
  <strong>Election:</strong>
  <%= @candidates.attached_election %>
</p>

<%if current_user && current_user.admin%>
<%= link_to 'Edit', edit_candidate_path(@candidates) %>
  <% end %>
<%= link_to 'Back to Candidates Page', candidates_path %>

src/test2/app/views/elections/edit.html.erb
<!--
// Project name: SOLVER
// Description: Create webapp that encourages students to vote and register to vote. Presents information
    about how to register and vote, and list of upcoming elections and candidates for those elections.
// Filename: elections\edit.html.erb
// Description: page to create edit election details
// Last modified on: 11/24/2019
-->


<h1>Edit Election</h1>

<%= form_with(model: @election, local: true) do |form| %>

  <% if @election.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@election.errors.count, "error") %> prohibited
        this election from being saved:
      </h2>
      <ul>
        <% @election.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :election_title %><br>
    <%= form.text_field :election_title %>
    <%= sanitize @election.election_title %>
  </p>

  <p>
    <%= form.label :election_date %><br>
    <%= form.date_select :election_date %>
  </p>

  <p>
    <%= form.label :election_type %><br>
    <%= form.text_field :election_type %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back to Election List', elections_path %>

src/test2/app/views/elections/index.html.erb
<!--
// Project name: SOLVER
// Description: Create webapp that encourages students to vote and register to vote. Presents information
    about how to register and vote, and list of upcoming elections and candidates for those elections.
// Filename: elections\index.html.erb
// Description: Presents list of elections after they've been created, and ability to edit and delete if user is admin
// Last modified on: 11/24/2019
-->


  <title>Election Page</title>



<h1>List of Elections</h1>


  <br>

  <!-- Search form -->
  <form class="form-inline">
    <i class="fas fa-search" aria-hidden="true"></i>
    <input class="form-control form-control-sm ml-3 w-70" type="text" placeholder="Search"
           aria-label="Search">
  </form>

  <br>



  <table class = "table table-striped">
  <tr>
    <th>Election Name</th>
    <th>Type</th>
    <th>Date</th>
    <th>Candidates</th>

  </tr>

  <% @elections.each do |election| %>
    <tr>
      <td><%= election.election_title %></td>
      <td><%= election.election_type %></td>
      <td><%= election.election_date %></td>
      <td><%= election.candidates_id %></td>
      <td><%= link_to 'Show', election_path(election) %></td>
      <%if current_user && current_user.admin%>
      <td><%= link_to 'Edit', edit_election_path(election) %></td>
      <td><%= link_to 'Delete', election_path(election),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
        <% end %>
    </tr>
  <% end %>
</table>


<p>
  <%if current_user && current_user.admin%>
  <%= link_to 'Add election', new_election_path %>
    <% end %>
</p>


<p>
  <%= link_to 'Back to Main Page', main_page_index_path %>
</p>

src/test2/app/views/elections/new.html.erb
<!--
// Project name: SOLVER
// Description: Create webapp that encourages students to vote and register to vote. Presents information
    about how to register and vote, and list of upcoming elections and candidates for those elections.
// Filename: elections\new.html.erb
// Description: page to create new election
// Last modified on: 11/24/2019
-->


<h1>New Election</h1>

<%= form_with scope: :election, url: elections_path, local: true do |form| %>

  <% if @election.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@election.errors.count, "error") %> prohibited
        this election from being added:
      </h2>
      <ul>
        <% @election.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <p>
    <%= form.label :election_title %><br>
    <%= form.text_field :election_title %>
  </p>

  <p>
    <%= form.label :election_date %><br>
    <%= form.date_select :election_date %>
  </p>

  <p>
    <%= form.label :election_type %><br>
    <%= form.text_field :election_type %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>



<%= link_to 'Back to Main Page', main_page_index_path %>

src/test2/app/views/elections/show.html.erb
<!--
// Project name: SOLVER
// Description: Create webapp that encourages students to vote and register to vote. Presents information
    about how to register and vote, and list of upcoming elections and candidates for those elections.
// Filename: elections\show.html.erb
// Description: page to show election details
// Last modified on: 11/24/2019
-->


<p>
  <strong>Election Title:</strong>
  <%= @election.election_title %>
</p>

<p>
  <strong>Election Date:</strong>
  <%= @election.election_date %>
</p>

<p>
  <strong>Election Type:</strong>
  <%= @election.election_type %>
</p>

<p>
  <strong>Candidates:</strong>
  <%= @election.candidates_id %>
</p>

<p>
  <strong>Election Description:</strong>
  <%= @election.description %>
</p>

<br><br><br>

<%if current_user && current_user.admin%>
<%= link_to 'Edit', edit_election_path(@election) %>
<% end %>
<%= link_to 'Back to Elections Page', elections_path %>

src/test2/app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

src/test2/app/views/layouts/application.html.erb
<!--
// Project name: SOLVER
// Description: Create webapp that encourages students to vote and register to vote. Presents information
    about how to register and vote, and list of upcoming elections and candidates for those elections.
// Filename: layouts\application.html.erb
// Description: file that sets default layout for each page in webapp
// Last modified on: 11/24/2019
-->


<!DOCTYPE html>
<html>
<head>
  <title>Test2</title>

  <!-- the three lines below import and serve the bootstrap libraries instead of using the bootstrap and jquerry3 gems
       this is due to an error the bootstrap gem was causing-->

  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <title>Register</title>

</head>

<!-- the below navbar section was learned from: https://getbootstrap.com/docs -->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/main_page/index">SOLVER</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/main_page/index">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/elections">Election List</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/candidates">Candidate List</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/pages">How to Register</a>
      </li>

    </ul>
  </div>
</nav>

<body>
<%= render 'layouts/alerts' %>
<div class="mx-3 mb-3">
  <%= yield %>
</div>
</body>

src/test2/app/views/layouts/default.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test2</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'default', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track': 'reload' %>

</head>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/main_page/index">SOLVER</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/main_page/index">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/elections">Election List</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">How to Register</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <title>Hello, world!</title>
</head>

</html>

src/test2/app/views/main_page/index.html.erb
<!--
// Project name: SOLVER
// Description: Create webapp that encourages students to vote and register to vote. Presents information
    about how to register and vote, and list of upcoming elections and candidates for those elections.
// Filename: main_page\index.html.erb
// Description: main/home page of webapp
// Last modified on: 11/24/2019
-->



<html>
  <title>Main Page</title>

<h1>SOLVER Welcome Page</h1>

<h2>Info:</h2>
  <br>
<p>
  This is the main page for the SOLVER Project (Student OnLine Voting Engagement and Registration)
</p>
<p>
  The project's goal is getting students registered to vote, as well as informing people about upcoming elections, the politicians who are running, and what their stances are.
  A large percentage of the population fails to go out and vote for most elections, meaning that their voices are unheard.
  People are more likely to go out and vote if they are informed about the elections and what the politicians are campaigning on.
</p>

  <% if current_user  %>
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> <!-- if user is signed in-->

  <% else %> <!-- if user isn't signed in-->
  <%= link_to "Sign Up", new_user_registration_path %>
  <%= link_to "Sign In", new_user_session_path %>
  <% end %>


  <br><br><br>
<p>
  Click here to see the project's GitHub page:
<form action="https://github.com/jbennet-t/SOLVER">
  <button type="submit">GitHub</button>
</form>
</p>

</html>

src/test2/app/views/pages/index.html.erb
<html>
<h1>How To Register</h1>


<p>

</p>
<body>
<p>
<h4>Qualifications For Voting</h4>
The criteria for being qualified to vote differs from state to state.
In order to register to vote in New Jersey, you must meet the following criteria:
<ol>
  <li>Be a United States Citizen</li>
  <li>Be at least 17 years old, though you are not permitted to vote till you have reached the age of 18</li>
  <li>Be a resident of the country for 30 days before the election</li>
  <li>Be a person not currently serving a sentence, probation, or parole because of a felony conviction</li>
</ol>

<!--
// Project name: SOLVER
// Description: Create webapp that encourages students to vote and register to vote. Presents information
    about how to register and vote, and list of upcoming elections and candidates for those elections.
// Filename: pages\index.html.erb
// Description: informational page containing details of how to register and vote, as well as links
// Last modified on: 11/24/2019
-->


<h4>Resources for Registering to Vote</h4>
<ul>
  <li><h6>How to Register By Mail</h6></li>
  You can register by mail-in form for any state in the US: <a href="https://www.eac.gov/voters/national-mail-voter-registration-form/"> National Mail Registration Form.</a>
  To register, simply download the form from the above page in you prefered language, and fill it out following the state-specific instructions for your state.
  Then, sign and seal the form in an envelope, and send to your state or local election office. Election offices can be found with a simple search,
  such as: "Election office address for 'MY STATE'"
  <li><h6>Polling Place Search</h6></li>
  In order to find your local voting location in New Jersey you can visit this site: <a href="https://www.eac.gov/voters/national-mail-voter-registration-form/">Polling Place Search </a>
  <li><h6>TCNJ Votes!</h6></li>
  Learn more about TCNJ's voting initiative: <a href="https://vote.tcnj.edu/">TCNJ Votes!</a>
  <li><h6>New Jersey Department of Elections</h6></li>
  This resource provides a lot of information about candidates, elections, and how, when, and where to vote in NJ:
  <a href="https://www.state.nj.us/state/elections/>Polling Place Search">New Jersey Division of Elections</a>

</ul>

</p>
</body>

<h5>Informational video for first time voters:</h5>

<iframe width="696" height="396" src="https://www.youtube.com/embed/JAI9vuvCads" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>



</html>